# Generated by Django 2.2.1 on 2019-05-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('rep_count', models.IntegerField(default=0, verbose_name='Times repeated')),
                ('last_rep_date', models.DateField(default=0, verbose_name='Last repetition')),
                ('location', models.TextField(help_text='e.g. URL or book title')),
                ('location_detail', models.TextField(help_text='e.g. section title or book page number')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Resource')),
            ],
        ),
    ]
