# Generated by Django 2.2.1 on 2019-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_added',
            field=models.DateField(verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='last_rep_date',
            field=models.DateField(verbose_name='Last repetition'),
        ),
    ]
