# Generated by Django 3.1.3 on 2020-12-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.TextField(blank=True, help_text='e.g. URL or book title', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.TextField(blank=True, help_text='e.g. section title or book page number', null=True),
        ),
    ]
