# Generated by Django 2.2.1 on 2019-05-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190529_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='date_added',
        ),
    ]
