# Generated by Django 3.1.4 on 2021-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_resource_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_hyperlink',
            field=models.BooleanField(default=True, help_text='Is location a live hyperlink?'),
            preserve_default=False,
        ),
    ]
