# Generated by Django 3.1.4 on 2021-01-01 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_resource_is_hyperlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='ReviewItem',
        ),
    ]
